### ISSUE TITLE
Replace branch-2.3.4-build by branch-2.3.4-build-new

### ISSUE THREAD

**Issue by Pierrotws** [TOSIT-IO/spark#5]
New branch branch-2.3.4-build-new has been created as replacement for 2.3.4 for following reasons:

- backport SPARK-28891 is REQUIRED to build (dist build, not jar build)
- release version 1.0 should be the last commit (or followed by a snapshot one)

**Comment by Pierrotws** [comment]
Also, documentation for flume was missing and reintegrated in tdp doc commit

**Comment by rpignolet** [comment]
Following the meeting, here my error when starting Spark 3 History Server:
```
ERROR [main:Logging@94] - Failed to bind HistoryServer
java.lang.IllegalStateException: class org.apache.hadoop.security.authentication.server.AuthenticationFilter is not a javax.servlet.Filter
        at org.sparkproject.jetty.servlet.FilterHolder.doStart(FilterHolder.java:103)
        at org.sparkproject.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.sparkproject.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:730)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:647)
        at org.sparkproject.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
        at org.sparkproject.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
        at org.sparkproject.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:910)
        at org.sparkproject.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
        at org.sparkproject.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
        at org.apache.spark.ui.ServerInfo.addHandler(JettyUtils.scala:491)
        at org.apache.spark.ui.WebUI.$anonfun$bind$3(WebUI.scala:148)
        at org.apache.spark.ui.WebUI.$anonfun$bind$3$adapted(WebUI.scala:148)
        at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
        at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
        at org.apache.spark.ui.WebUI.bind(WebUI.scala:148)
```

In the previous TDP release here a grep for `jar`:
```
find spark-3.2.2-0.0-bin-tdp -name *javax*
spark-3.2.2-0.0-bin-tdp/licenses/LICENSE-javax-transaction-transaction-api.txt
spark-3.2.2-0.0-bin-tdp/jars/javax.servlet-api-3.1.0.jar
spark-3.2.2-0.0-bin-tdp/jars/javax.jdo-3.2.0-m3.jar
spark-3.2.2-0.0-bin-tdp/jars/javax.inject-1.jar
```

`javax.servlet-api` is missing in the new branch but I look at Apache binaries release of Spark 3 and these `jar` are missing too. I don't know how the Apache Spark binary release can work.
